name: "EmpowerJS update and publish"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'chain/proto/**' # On updating proto
      - 'frontend/empowerjs/src/**' # On updating empowerjs source files

jobs:
  build:
    name: Update and publish empowerjs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.22

      - run: earthly --ci --output +generate-schema
        working-directory: ./cosmwasm

      - run: earthly --ci --output +codegen-all
        working-directory: ./frontend/empowerjs

      #- run: earthly --ci --output +publish-empowerjs --NPM_TOKEN="$NPM_TOKEN"
      #  env:
      #    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #  working-directory: ./frontend

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: "Set up node"
        uses: actions/setup-node@v3
        if: steps.verify_diff.outputs.changed != 'true'
        with:
          node-version: '18'
      - name: Publish empowerjs
        if: steps.verify_diff.outputs.changed != 'true'
        working-directory: ./frontend
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npx lerna publish patch --yes --no-private --contents empowerjs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update empowerjs
          title: Update empowerjs
          branch: update-empowerjs
      
