name: "Build and push devnet to ghcr.io"

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    # paths:
    #   - 'chain/**'

env:
  IMAGE_NAME: empowerchain-devnet

jobs:
  build:
    name: Build and push devnet to ghcr.io
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: earthly/actions-setup@v1
        with:
          version: 0.6.30

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: build and push image
        run: earthly --ci --push +devnet --IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        working-directory: ./chain