name: "Devnet depoly"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Devnet
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy Devnet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEVNET_HOST }}
          username: ${{ secrets.DEVNET_USER }}
          password: ${{ secrets.DEVNET_PASSWORD }}
          port: ${{ secrets.DEVNET_PORT }}
          script: |
            source .zshrc
            ./deploy.sh
