name: "Docs update"

on:
  push:
    branches:
      - main
    paths:
      - 'chain/proto/**' # On updating proto

jobs:
  build:
    name: Update EmpowerChain swagger docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions-setup@v1
        with:
          version: 0.6.30

      - run: earthly --ci --output +docs-gen-all
        working-directory: ./docs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update Swagger docs
          title: Update Swagger docs
          branch: update-docs
          labels: C:docs
