name: "Pull Request"

on:
  pull_request:


jobs:
  build:
    name: Build EmpowerChain
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.22

      - run: earthly --ci +build

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.22

      - run: earthly --ci +lint

  test:
    name: Test EmpowerChain
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.22

      - run: earthly --ci +test

      - run: earthly --ci +smoketest